### ISSUE TITLE
Type-A IPのStepper MotorをY,L,Tの自由度で動くスクリプトを作る

### ISSUE THREAD

**Issue by Takahiro0714** [MiyoKouseki/epics-equipments-control#10]
## 目的
IPのモーターで動く自由度はYaw, Long, Transなのだが現状モーターを一つづつしか動かすことできないので、各自由度に動かせるようにスクリプトを作る。
最終的には、MEDMに実装して動作試験も行う。

## Todo
- [x] controlInvertedPendulum.pyに各自由度のモーター動作させる命令をかく。
- [ ] ipython上で上記の定義式が動作することを確認する。
- [ ] 動作試験するための日時を決める
- [ ] IP用のMedmの作成
- [ ] medm上での動作試験

**Comment by MiyoKouseki** [comment]
これは正田さんがやった気がする。
