### ISSUE TITLE
一般的な測定機器に拡張

### ISSUE THREAD

**Issue by MiyoKouseki** [MiyoKouseki/epics-equipments-control#15]
Keysightのシグナルジェネレータ（E8663D PSG）のパラメータ値を監視したいという要望がきた。

幸い、この機器はTelnet越しにSCPIコマンドで通信ができるみたいなので、値を取得するのは直ぐできそう。

なのでIOCを立ててそこにcaputすればEPICS上で監視することができる。一応ここまでが最低限。

更にやるとすれば、SDFで監視できるようにできれば、思わぬ値の変更を検知して知らせてくれるので精神的負担が減る。

ToDo
 - [x] 要件の定義

1) 周波数を変えるコマンドの用意
 - [x] e8663d.pyをk1ctr7でまず動かして、動作チェック。
 - [x] k1scriptで動作確認
 - [x] 完了

2) Sweepしているときに周波数を読めるようにしてEPICSに書き込む用意
 - [x] モニターするチャンネル名を決める。
 - [x] どっかのモデルにepicsチャンネル用のパーツを貼って、チャンネルを生成。
 - [ ] SDFで監視。
 - [ ] 完了

**Comment by MiyoKouseki** [comment]
ちなみにSDFでは、文字列のEPICSチャンネルとかも検知してくれるのだろうか。

**Comment by YutaroEnomoto** [comment]
**= 要件定義のようなもの =**
* ':FREQuency:FIXed xxxMHZ'、'FREQuency:FIXed UP|DOWN'といったコマンドを利用して、離散的な周波数スイープができる。
* ':FREQuency:SYNThesis:SWEep' 的なのを使って、Continuous phaseなモードで連続的なスイープができる。
* 上記2つが、k1scriptやk1grd0 (?) で使えるpythonモジュール (?)になっている。
import miyoFGってしたら、
miyoFG.up(10) # 10Hz up
miyoFG.up(-10) # 10Hz down
miyoFG.set(40.0272e6) # set to 40.0272 MHz
miyoFG.sweep(<start>,<stop or TARGet>,<RATE>)  # start Hzからstop Hzまで RATEの速さでスイープする。
みたいなのが使えるイメージ？ですかね。
* ':FREQuency:SYNThesis:SWEep:FREQuency?'や':FREQuency:FIXed?'的なコマンドで現在の周波数を取得し、EPICSに流してDQする。

* 1月にはもう1台くるので、
X = miyoFG('IP1')
X.up(10) # X arm用のFGを10Hz up
Y = miyoFG('IP2')
Y.up(-10) # Y arm用のFGを10Hz down
的なことができるようにしておく。

**Comment by MiyoKouseki** [comment]
from keysight import VoltageControlledOscillator

https://github.com/MiyoKouseki/epics-equipments-control/blob/12fc0ee87f1197fffad7db2ae9683fd51fdff486/keysight/e8663d.py#L92

**Comment by YutaroEnomoto** [comment]
* set(value, Unit)
set(40, MHZ) ってすると、:FREQuency:FIXed 40MHZ で周波数をセットできる。
(optional) なんか、おかしな値 (桁間違い) とかを防ぐために、指定できる周波数の範囲を指定できるといいかもね。この機能はいらない気もする。

* step(value, Unit)
step(100, Hz)ってすると、
:FREQuency:STEP 100HZ
:FREQuency:FIXed UP
をしてくれる。
step(-100, Hz)ってすると、
:FREQuency:STEP 100HZ
:FREQuency:FIXed DOWN
をしてくれる。

* sweep(start,stop,rate)
:FREQuency:SYNThesis:SWEep:RATE rate
:FREQuency:SYNThesis:SWEep:TARGet stop
:FREQuency:FIXed start
:FREQuency:SYNThesis:SWEep:STATe STARt
以上の順で行い、スイープを開始してくれる。
(optional) :FREQuency:SYNThesis:SWEep:STATe? の結果 (スイープの状態) を保存するEPICSチャンネルがあると良いかもね。これはあると助かる気がする。

**Comment by MiyoKouseki** [comment]
あとは実際にコマンドを送るところまで実装。e8663dのここのコメントアウトを外せばいい。
https://github.com/MiyoKouseki/epics-equipments-control/blob/e40ae6c5b87b2f4dda00878b143a04222fcd6005/keysight/e8663d.py#L59


使い方の例
https://github.com/MiyoKouseki/epics-equipments-control/blob/e40ae6c5b87b2f4dda00878b143a04222fcd6005/keysight/e8663d.py#L165-L181

**Comment by YutaroEnomoto** [comment]
メモ:
周波数をEPICSに残したい目的
1. ALSによる共振点探しの際に記録したい (Guardianによる)
2. キャビティスキャンの際に記録したい

for 1.  --> Guardianにcaput を仕込む
for 2. --> キャビティスキャンスクリプトを組んで、その中にcaputを仕込む

**Comment by MiyoKouseki** [comment]
k1grd0にPyvisaをインストールする話だったけど、それは最終手段にして、Picomotorと同じように動かすことにする。こっちのほうがPicomotorのメンテと一緒にできてなにかと楽なので。

そのため、どういうチャンネルが必要か考える。こんな感じ？（デザインとか配置はテキトー）
![image](https://user-images.githubusercontent.com/24282734/55122657-04669080-5143-11e9-87da-aecb9f4c8a56.png)

**Comment by MiyoKouseki** [comment]
https://github.com/MiyoKouseki/epics-equipments-control/tree/master/keysight

- [x] PCASを追加した。FGを動かすところはコメントアウトしている。
とりあえずこれで、picoと同じように動かせる。
- [ ] ＿FREQに値を書き込む別のスクリプトはまた今後。

**Comment by YutaroEnomoto** [comment]
Channel names for the monitored frequencies of FG:
'ALS-'+arm+'_BEAT_LO_FREQ'  |  arm = 'X' or 'Y'

**Comment by YutaroEnomoto** [comment]
- [ ] 結局、どのプロセスがFGに周波数を聞きに行くんだっけ？ k1grd0にpyvisaが入ってない・入れないのなら、pcasのなかに周波数をたずねてEPICSに書き込むやつが def writeの中に用意しなければ。
- [ ] picomotorのように、複数台のFGに対応したものにしたい。(そろそろ2台同時に使う)
- [ ] pcasのプロセスが走っている途中に、web browser等からLocal keyを押されるとEPICSがコケるような雰囲気がある。

**Comment by YutaroEnomoto** [comment]
Local keyを押したあとに FIX_GO ONとかを行うことができない。

**Comment by YutaroEnomoto** [comment]
medmを作った。
$(USERAPPS)/cds/common/medm/keysight/HAPPY_FUNCTION_GENERAOTR.adl

**Comment by MiyoKouseki** [comment]
とりあえず、動くものはつくったのでClose。今後新しいバグが出てきたら新規にIssueを立ち上げる。
