### ISSUE TITLE
Cryo Stepping Motor 試験機の準備

### ISSUE THREAD

**Issue by Takahiro0714** [MiyoKouseki/epics-equipments-control#9]
## 目的
解析棟でCryoSteppingMotor試験機を準備し、リモートで動作させることを確認する。

## Todo
- [x] モーターの準備
- [x] コントローラーの準備
- [x] 電源の確保
- [ ] 有線LANケーブルの準備（短くて良い）
- [ ] 初期の動作確認のためWindowsーPCの準備
- [x] 試験場所の確保

**Comment by MiyoKouseki** [comment]
おそらく宮本さんがすでにやってる
